
export STAGING_DIR = /home/fumon/openwrt/build_dir/target-mips_r2_uClibc-0.9.33.2/OpenWrt-SDK-ar71xx-for-unknown-x86_64k-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir
export PATH := $(PATH):/home/fumon/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/OpenWrt-SDK-ramips-for-unknown-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin
export TOOL = $(STAGING_DIR)/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
export SDK = $(STAGING_DIR)/target-mipsel_24kec+dsp_uClibc-0.9.33.2

BINARY = listen

OBJS = $(BINARY).o
OBJS += arduino-serial-lib.o hsl_to_rgb.o

LIBS += -lm

CC = mipsel-openwrt-linux-gcc
LD = mipsel-openwrt-linux-gcc

CFLAGS += -Os -Wall -Wextra -I$(SDK)/usr/include
# CFLAGS += -ggdb3
LDFLAGS += -L$(SDK)/usr/lib -L$(TOOL)/lib -L$(TOOL)/usr/lib -Wl,-rpath=$(TOOL)/lib $(LIBS)

all: exe

exe: $(BINARY).exe

%.exe: $(OBJS) 
	$(LD) -o $(*) $(OBJS) $(LDFLAGS)

%.o: %.c Makefile
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f *.o
	rm -f $(BINARY)

.PHONY: exe clean
